//GET
### todos los clientes
GET http://localhost:1234/usuarios
### clientes por id
GET http://localhost:1234/usuarios/id
### todos los productos
GET http://localhost:1234/productos
### producto por id
GET http://localhost:1234/productos/id



//POST
### nuevo cliente
POST http://localhost:1234/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzdWFyaW8iOiJwYWJsb2FsZWphbmRyb2UiLCJuaXZlbCI6MSwiZXhwIjoxNjk2NTQ2OTA4ODcyLCJpYXQiOjE2OTY1NDY4NDh9.aFKLkTEtex16pRGj4vT1Dde76KyNEXCmxWwabS0uPvo

{
    "nombre": "Caja negra de jugar",
    "precio": 325.00
}

### nuevo producto
POST http://localhost:1234/producto/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzdWFyaW8iOiJqdWFucGVyZXoiLCJuaXZlbCI6MSwiZXhwIjoxNjk3MTI5NTQ2MjMzLCJpYXQiOjE2OTcxMjkzMDZ9.f93e70Os8gIqwaqKaSKq1F09C1NQ-rEI3hWk8nq3qKQ

{
  "nombre": "Diego Hojoredondo",
  "edad":28,
  "email": "michimiau@siosi.com",
  "telefono": "+1 323-489-7890",
  "usuario":"diegohojoredondo",
  "password":"diegopass",
  "nivel": 1
}

//PATCH
### modificar producto
PATCH http://localhost:1234/usuarios/id
Content-Type: application/json

{
  "nombre": "Cara Clarinetes"
}
### modificar producto
PATCH http://localhost:1234/productos/id
Content-Type: application/json

{
    "nombre": "Mixer multiuso ACME PODEROSO"
}

//DELETE
### borrar usuario
DELETE http://localhost:1234/usuarios/id
### borrar producto
DELETE http://localhost:1234/productos/id




### Request desde el formulario de logueo en el frontend
POST http://localhost:1234/auth
Content-Type: application/json

    {
        "usuario": "juanperez",
        "password": "juanpass"
    }



